### ISSUE TITLE
haproxy does not reference upstream image README

### ISSUE THREAD

**Issue by gtkramer** [clearlinux/dockerfiles#131]
@sophia0328, can you follow what was done for the golang image and reference the upstream haproxy README?

**Comment by sophia0328** [comment]
@gtkramer Done. please help to review [#132](https://github.com/clearlinux/dockerfiles/pull/132)

**Comment by sophia0328** [comment]
One typo in #132 , please review [#133](https://github.com/clearlinux/dockerfiles/pull/133). Thanks.

**Comment by gtkramer** [comment]
Thank you, @sophia0328 !
