### ISSUE TITLE
ciao-deploy: Do not install roles from ansible galaxy

### ISSUE THREAD

**Issue by albertomurillo** [clearlinux/dockerfiles#14]
ciao-deploy container is installing roles from ansible galaxy.

Those roles are no longer needed with the migration of the ciao deployment scripts from clear-configmanagement to ciao repository.

**Comment by mrkz** [comment]
What's should be the flow with the migration of the roles?
Will ansible look up for them in /root/ciao/_DeploymentAndDistroPackaging/ansible automatically or... ?

**Comment by albertomurillo** [comment]
ansible looks for roles in the current directory.
The instructions already includes
`cd  /root/ciao/_DeploymentAndDistroPackaging/ansible`

Where a `roles` directory already exists

**Comment by mrkz** [comment]
@albertomurillo please comment on PR prior to merge

**Comment by albertomurillo** [comment]
+1
