### ISSUE TITLE
clearlinux/php-fpm curl command fails for SSL certificate problem

### ISSUE THREAD

**Issue by sophia0328** [clearlinux/dockerfiles#188]
clearlinux/php-fpm container adds bundle curl, then in the container bash env to run curl command fails:

in clearlinux/php-fpm Dockerfile:
RUN source /os-release && \
    mkdir /install_root \
    && swupd os-install -V ${VERSION_ID} \
    --path /install_root --statedir /swupd-state \
    --bundles=os-core-update,php-basic,curl --no-scripts

then run the container and curl command:
docker run -it clearlinux/php-fpm bash
curl -O https://wordpress.org/latest.tar.gz

get error log:
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.

**Comment by qzheng527** [comment]
That is probably because "os-install --no-scripts". 
With "--no-scripts" no post scripts would be executed.
Replacing "--no-scripts" with "--no-boot-update", this issue was gone.
