### ISSUE TITLE
Questions about enable_materialized_views and enable_transient_replication

### ISSUE THREAD

**Issue by hh-project-config** [clearlinux/dockerfiles#204]
Thanks for providing this useful [container](https://hub.docker.com/r/clearlinux/cassandra). 

I have a question about two cassandra configs: `enable_materialized_views` and `enable_transient_replication.` It seems the [official document](http://cassandra.apache.org/doc/latest/configuration/cassandra_config_file.html) says "Materialized views are considered experimental and are not recommended for production use." And the default value for these two parameters are **False** in the document. They say they will disable them in Cassandra 4.

However, in the latest version of Cassandra (3.11.4), the default value for them are still **True**, as is the setting in your container's cassandra.yaml. 

Shall we disable them manually for now? 
Thanks!

**Comment by wxb071216** [comment]
In general clearlinux cassandra docker image will keep config setting consistent with the official cassandra docker image in docker hub, we will follow the change if Cassandra 4 disable them.
