### ISSUE TITLE
Correct FROM link for the latest DLRS/mkl dockerfile

### ISSUE THREAD

**Issue by cigoic** [clearlinux/dockerfiles#222]
Found TWO statements inside stacks/dlrs/mkl/Dockerfile:

`FROM stacks-clearlinux:......`

should be corrected as shown below:

`FROM clearlinux/stacks-clearlinux:......`

Prefix **"clearlinux/"** in front of stacks-clearlinux, otherwise, it will require us to login Docker account to build the image.

**Comment by joselamego** [comment]
@cigoic: Thank you for your report. We will update the base image name.

**Comment by joselamego** [comment]
Fixed in latest version.
