### ISSUE TITLE
Questions about my.cnf of MariaDB

### ISSUE THREAD

**Issue by timlackhan** [clearlinux/dockerfiles#244]
Hello everyone. 
Recent days I deployed clearlinux/MariaDB container on kubernetes and I found the file my.cnf doesn't work. So I had to add args field to my deployment yaml file. I just suspected my.cnf is not read by MariaDB. 
Thanks!

**Comment by ZhongbaoShi** [comment]
Could you help to compare my.cnf with your my.cnf in mariadb-deployment-conf.yaml? maybe some configuration need be changed?

**Comment by timlackhan** [comment]
Thanks everyone and I have fixed this problem successfully!
