### ISSUE TITLE
update nginx README

### ISSUE THREAD

**Issue by mrkz** [clearlinux/dockerfiles#271]
On latest nginx Dockerfile update (https://github.com/clearlinux/dockerfiles/commit/d7b52070b2514bdb07b5029bdc0e4bfa38ea5ec2) the directories of a working nginx setup were moved from `nginx` to `nginx-mainline` but the README documentation still refers to `nginx` based directories (e.g: `/etc/nginx/conf.d/`, etc).

this documentation should be updated to reflect changes on the `Dockerfile` as well.

**Comment by qzheng527** [comment]
For general users, they don't care about the nginx-mainline. To make the clearlinux/nginx container compatible with the general way ( conf files in /etc/nginx/conf.d/ ) we added a link in the Dockerfile as below. 
"
    # add links to make it compatible with general name nginx
    ln -sf /var/log/nginx-mainline /var/log/nginx && \
    ln -sf /var/lib/nginx-mainline /var/lib/nginx && \
    ln -sf /etc/nginx-mainline /etc/nginx && \
    ln -sf /usr/bin/nginx-mainline /usr/bin/nginx && \
"
So to users, they can still use what they are familiar way to put the customized conf files to /etc/nginx/conf.d/ for clearlinux/nginx container.
