### ISSUE TITLE
Where did openjdk for version 8 image go? 

### ISSUE THREAD

**Issue by karol-brejna-i** [clearlinux/dockerfiles#282]
Why there is only one tag for openjdk image (latest)?

It would be good if we had images for dedicated versions of Java...

**Comment by ZhongbaoShi** [comment]
Thanks your good suggestions, @karol-brejna-i. 
Currently, only latest tag is supporting by Clear Linux container, which point to latest openjdk12 version. After openjdk8, there are several IA optimization feature integrated to openjdk, such as AVX512, MA(fused multiply–add)  Vectorization, SHA256 optimization by using AVX2... We expected to gain more performance benefit from openjdk upgrade on IA platform.   

Of course, we are planning to have tag support for multi-version openjdk container during Q4. 
Before that, if you still want to use openjdk8 Clear container, maybe you can revert 1 commit [0b5f343](https://github.com/clearlinux/dockerfiles/commit/0b5f343bad26bd114bf15a410b892aeae98ab9f6#diff-a315d8f2714028b215f97a9ef8dfc99b) and rebuild to have openjdk8 container image locally.

**Comment by karol-brejna-i** [comment]
@ZhongbaoShi, 
Thank you for the quick response.

> Of course, we are planning to have tag support for multi-version openjdk container during Q4.
> Before that, if you still want to use openjdk8 Clear container, maybe you can revert 1 commit [0b5f343]

Yeah, I did the exact thing you are suggesting ;-)

>After openjdk8, there are several IA optimization feature integrated to openjdk, such as AVX512, 
> MA(fused multiply–add) Vectorization, SHA256 optimization by using AVX2.

Seems like very interesting stuff! Need to do more reading on this...

Thanks again!

**Comment by qzheng527** [comment]
@karol-brejna-i 
We have clearlinux/openjdk:8 online now.
[link](https://hub.docker.com/repository/docker/clearlinux/openjdk)

You could download and try. :)
