### ISSUE TITLE
travis: Fix Travis CI automation

### ISSUE THREAD

**Issue by obedmr** [clearlinux/dockerfiles#31]

**Comment by shrmrf** [comment]
@obedmr are you looking to just build the `clearlinux/keystone` container or all of the containers in this repo? If it's the latter, may I propose using the `env` key to store the locations of all the directories?

the `env` key would sorta look like this:

```yaml
env:
  - DOCKERFILE_DIR=ciao-common
  - DOCKERFILE_DIR=ciao-controller
  - DOCKERFILE_DIR=ciao-launcher
  - DOCKERFILE_DIR=ciao-scheduler
  - DOCKERFILE_DIR=ciao-deploy
  - DOCKERFILE_DIR=ciao-webui
  - DOCKERFILE_DIR=clr-sdk
  - DOCKERFILE_DIR=machine-learning
  - DOCKERFILE_DIR=machine-learning-ui
  - DOCKERFILE_DIR=mixer-ci
  - DOCKERFILE_DIR=keystone
  - DOCKERFILE_DIR=mariadb
```

and `before_script` might look like:
```yaml
before_script:
  - cd $DOCKERFILE_DIR
  - docker build -t clearlinux/$DOCKERFILE_DIR .
```

**Comment by shrmrf** [comment]
You can always do the "special" stuff in the `script` and `deploy` keys.

I have travis running on my fork here: https://travis-ci.com/shrmrf/dockerfiles

CC @bryteise

**Comment by obedmr** [comment]
@shrmrf at the beginning that was the only image that was required to build in an automated way. And sure, it make sense now to make it for the rest of the images. I'm not in charge of this automation anymore. @bryteise  or @mrkz  could give more input now. As far I remember I passed the dockerhub automation ownership to them.

**Comment by shrmrf** [comment]
Aaah.. I just realized that this is an issue not only from September, but September 2017 :1st_place_medal:

**Comment by bryteise** [comment]
@shrmrf Thanks for the fix!

**Comment by shrmrf** [comment]
@bryteise I believe that you might also need to reenable Travis CI integration/app for the repo. The last build seems to be from 2 years ago.

**Comment by bryteise** [comment]
Yes indeed, building underway so we'll see how it goes.
