### ISSUE TITLE
postgresql 12

### ISSUE THREAD

**Issue by chriseomi** [clearlinux/dockerfiles#333]
Would be nice to run latest stable PG 12.1 on clear. Any plans to update the docker image? Not sure how else one would deploy.

**Comment by ZhongbaoShi** [comment]
Clear Linux has Postgres 9 (https://github.com/clearlinux-pkgs/postgresql) and Postgres 11 package (https://github.com/clearlinux-pkgs/postgresql11) available now. But, no Postgres 12 package available yet. 
Before we have postgresql 12 docker image, we need add postgres12 package into Clear firstly. 

Do you have user case to require postgresql12 now?

**Comment by chriseomi** [comment]
Thanks for asking. The need was not urgent, so went with a lower version. That said, maybe there are other first-timers may also install CL and think. "Hmm why isnt the latest version of a popular package available?"

**Comment by bryteise** [comment]
Should be in the next release as postgreql12.
