### ISSUE TITLE
Error running without `--native` inside container

### ISSUE THREAD

**Issue by shrmrf** [clearlinux/dockerfiles#37]
### Environment
I run the `clr-sdk` container with `-v /var/run/docker.sock:/var/run/docker.sock`

### Problem
I get the following error if I try to run `sudo mixer build all`. The `/var/run/docker.sock` has been correctly mapped inside of the container and the communication with the `docker` daemon works.

```console
clr@70098d6eb3ac ~/mix $ sudo mixer build all
Warning: Using Format=25 from mixer.state for this build.
Updating docker image
25: Pulling from clearlinux/mixer
Digest: sha256:183aa6045775b3becb4ebdd499afdd4440d5b00feebf2947df8b7138b4847fc1
Status: Image is up to date for clearlinux/mixer:25
Running command in container: "mixer build all"
docker: Error response from daemon: error while creating mount source path '/home/clr/mix': mkdir /home/clr: permission denied.
ERROR: Failed to run command in container: failed to execute docker run -i --network=host --rm --workdir /home/clr/mix --entrypoint mixer -v /home/clr/mix:/home/clr/mix clearlinux/mixer:25 build all --native: exit status 126
```

I suspect that running `sudo mixer build all` has the effect of passing the _current_ path to be shared with the docker daemon whereas the _current_ path in the current context doesn't exist on the host.

I think we should just remove the info around `/var/run/docker.sock` because it might lead to false hopes.

**Comment by kevincwells** [comment]
Sorry @shrmrf -- just saw this now.

You're right -- there is the added complexity that the path in the container needs to match the path on the host, as it's the host's docker daemon that will be interpreting the path. It's definitely a complicated setup, but it's possible to make it work.

For example, the initial host run of `clr-sdk` needs to mount `-v /home/shrmrf/mixdir:/home/shrmrf/mixdir`, _not_ `-v /home/shrmrf/mixdir:/home/clr/mix` like the regular instructions suggest.

**Comment by kevincwells** [comment]
I happened to have a PR (#39) outstanding that was already updating the `README`, so I added a sentence about this topic to the docker socket section.

**Comment by shrmrf** [comment]
Cool!! I think we can close this issue because PR #39 will take care of it when merged 👍 

Thanks again @kevincwells !!
