### ISSUE TITLE
Latest mixer

### ISSUE THREAD

**Issue by aaronovz1** [clearlinux/dockerfiles#40]
How often does the docker image get rebuilt? I'm looking to get the latest mixer version. Do I need to build clr-sdk container locally for this or can someone push an updated container to dockerhub?

**Comment by shrmrf** [comment]
you could do a `swupd update` inside the `clr-sdk` container to get the latest tools, or build it yourself..

**Comment by aaronovz1** [comment]
I ended up building it myself which worked great. Thanks.
