### ISSUE TITLE
The docker image for kube tfjobs doesn't exist

### ISSUE THREAD

**Issue by qzheng527** [clearlinux/dockerfiles#71]
Hi,

I basically followed the link below to try Deep Learning stack.
https://clearlinux.org/documentation/clear-linux/tutorials/dlrs

Everything works except on the last steps, run the TF jobs.
The docker image "hub.docker.com/clearlinux/stacks-dlrs-kubeflow:latest" defined in the https://github.com/clearlinux/dockerfiles/tree/master/stacks/dlrs/kubeflow/dlrs-tfjob/dlrs-bench/prototypes/*.jsonnet doesn't exist.
Heard from From IRC (#intel-verticals) I modified the image to "hub.docker.intel.com/clearlinux/stacks-dlrs-kf-tfjob-mkl:latest". It can pull the image successfully.
But the eventually still got errors.
Looks like  the absl module is not installed on the image.
Can someone have a check on it?
Thanks.

clrdev@zhengq-station ~/kflow/kflow_app $ kubectl get pods -n ${K8S_NAMESPACE}
NAME                                        READY   STATUS    RESTARTS   AGE
dlrsalexnet-ps-0                            0/1     Error     0          14m
dlrsalexnet-worker-0                        0/1     Error     0          14m
dlrsalexnet-worker-1                        0/1     Error     0          14m
dlrsalexnet-worker-2                        0/1     Error     0          14m
tf-job-dashboard-679c5f984d-72mcn           1/1     Running   0          15m
tf-job-operator-v1alpha2-674b584564-b72dg   1/1     Running   0          15m
clrdev@zhengq-station ~/kflow/kflow_app $ kubectl logs -n ${K8S_NAMESPACE} -f dlrsalexnet-ps-0
INFO|2019-01-24T05:53:39|/opt/launcher.py|63| Launcher started.
INFO|2019-01-24T05:53:39|/opt/launcher.py|78| Command to run: python tf_cnn_benchmarks.py --batch_size=32 --model=alexnet --variable_update=parameter_server --local_parameter_device=cpu --init_learning_rate=0.0001 --tf_random_seed=8286 --device=cpu --data_format=NHWC --job_name=ps --ps_hosts=dlrsalexnet-ps-0:2222 --worker_hosts=dlrsalexnet-worker-0:2222,dlrsalexnet-worker-1:2222,dlrsalexnet-worker-2:2222 --task_index=0
INFO|2019-01-24T05:53:39|/opt/launcher.py|30| Running python tf_cnn_benchmarks.py --batch_size=32 --model=alexnet --variable_update=parameter_server --local_parameter_device=cpu --init_learning_rate=0.0001 --tf_random_seed=8286 --device=cpu --data_format=NHWC --job_name=ps --ps_hosts=dlrsalexnet-ps-0:2222 --worker_hosts=dlrsalexnet-worker-0:2222,dlrsalexnet-worker-1:2222,dlrsalexnet-worker-2:2222 --task_index=0
INFO|2019-01-24T05:53:39|/opt/launcher.py|42| b'Traceback (most recent call last):'
INFO|2019-01-24T05:53:39|/opt/launcher.py|42| b'File "tf_cnn_benchmarks.py", line 25, in <module>'
INFO|2019-01-24T05:53:39|/opt/launcher.py|42| b'from absl import app'
INFO|2019-01-24T05:53:39|/opt/launcher.py|42| b"ModuleNotFoundError: No module named 'absl'"
Traceback (most recent call last):
  File "/opt/launcher.py", line 84, in <module>
    run_and_stream(command)
  File "/opt/launcher.py", line 54, in run_and_stream
    " ".join(cmd), process.returncode))
ValueError: cmd: python tf_cnn_benchmarks.py --batch_size=32 --model=alexnet --variable_update=parameter_server --local_parameter_device=cpu --init_learning_rate=0.0001 --tf_random_seed=8286 --device=cpu --data_format=NHWC --job_name=ps --ps_hosts=dlrsalexnet-ps-0:2222 --worker_hosts=dlrsalexnet-worker-0:2222,dlrsalexnet-worker-1:2222,dlrsalexnet-worker-2:2222 --task_index=0 exited with code 1

**Comment by joselamego** [comment]
Thank you for your report. We are looking at it.

**Comment by DnPlas** [comment]
We've made some changes recently and the TFJobs are now set up using a custom image that you pass via a ksonnet flag. Mind trying to run TFJobs again with the new set of instructions from the DLRS tutorial?

**Comment by joselamego** [comment]
@qzheng527: did previous advice solve the issue for you? if so, Are you ok with us closing this report?
